name: Build Mesa
description: Build mesa
inputs:
  sconsflags:
    default: ""
  working-directory:
    default: .
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Building with flags:" ${{ env.SCONSFLAGS }}
        scons ${{ env.SCONSFLAGS }}
