name: Build and package
on:
  workflow_dispatch:

# Global Settings
env:
  SCONSFLAGS: 
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  build:
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: build-scarlett
            sconsflags: cppdefines=_GAMING_XBOX_SCARLETT extra_suffix=scarlett
            build: 1
            archive: bin/*.lib

          - name: build-x86
            sconsflags: arch=x86_32
            build: 1
            archive: bin/*.lib

          - name: build-x64
            sconsflags: arch=x86_64
            build: 1
            archive: bin/*.lib

          - name: build-arm64
            sconsflags: arch=arm64
            build: 1
            archive: bin/*.lib

          - name: source
            sconsflags:
            build: 0
            archive: godot-mesa

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dependencies
        uses: ./.github/actions/deps

      - id: get-mesa-sha1
        shell: bash
        working-directory: godot-nir-static/mesa
        run: |
          val=$(git rev-parse HEAD)
          echo "sha=$val" >> $GITHUB_OUTPUT

      - shell: bash
        working-directory: godot-nir-static
        run: |
          ./update_mesa.sh
        env:
          PYTHONPYCACHEPREFIX: ${{ github.workspace }}/build/__pycache__
          MESA_GIT_SHA1_OVERRIDE: ${{ steps.get-mesa-sha1.outputs.sha }}

      - name: Compilation
        if: ${{ matrix.build == 1 }}
        uses: ./.github/actions/build-mesa
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          working-directory: godot-nir-static

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: godot-nir-static/${{ matrix.archive }}
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: src/bin
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          name: source
          path: src/godot-mesa

      - id: get-version
        shell: bash
        run: |
          set -x
          version=$(cat src/godot-mesa/VERSION.info|head -n1|tr -d \\n|tr -d \\r)
          height=$(git log --oneline $version..HEAD 2>/dev/null|wc -l || echo "0")
          tagname=${version}-${height}
          if [[ x"$height" == x"0" ]]; then
            tagname=${version}
          fi
          echo "tagname=$tagname" >> $GITHUB_OUTPUT

      - name: Zip ${{ steps.get-version.outputs.tagname }}
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: godot-nir-${{ steps.get-version.outputs.tagname }}.zip
          directory: src/

      - name: Release ${{ steps.get-version.outputs.tagname }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: src/godot-nir-${{ steps.get-version.outputs.tagname }}.zip
          tag: ${{ steps.get-version.outputs.tagname }}
          commit: ${{ github.sha }}
          draft: false
          makeLatest: true