name: Build and package
on:
  workflow_dispatch:

# Global Settings
env:
  SCONSFLAGS: 
  SCONS_CACHE_MSVC_CONFIG: true

jobs:
  build:
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: build-scarlett
            sconsflags: defines=_GAMING_XBOX_SCARLETT extra_suffix=scarlett
            build: 1
            archive: bin/*.lib

          - name: build-x86
            sconsflags: arch=x86_32
            build: 1
            archive: bin/*.lib

          - name: build-x64
            sconsflags: arch=x86_64
            build: 1
            archive: bin/*.lib

          - name: build-arm64
            sconsflags: arch=arm64
            build: 1
            archive: bin/*.lib

          - name: source
            sconsflags:
            build: 0
            archive: godot-mesa

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dependencies
        uses: ./.github/actions/deps

      - shell: bash
        working-directory: godot-nir-static
        run: |
          rm -f godot-mesa/bin/git_sha1.h
          ./update_mesa.sh
        env:
          PYTHONPYCACHEPREFIX: ${{ github.workspace }}/build/__pycache__

      - name: Compilation
        if: ${{ matrix.build == 1 }}
        uses: ./.github/actions/build-mesa
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          working-directory: godot-nir-static

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: godot-nir-static/${{ matrix.archive }}
          retention-days: 1

  archive:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: src/bin
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          name: source
          path: src/godot-mesa

      - id: get-version
        shell: bash
        run: |
          version=$(cat src/godot-mesa/VERSION.info|head -n1|tr -d \\n|tr -d \\r)
          echo "version=$version" >> $GITHUB_OUTPUT

      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: godot-nir-${{ steps.get-version.outputs.version }}.zip
          directory: src/

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: src/godot-nir-${{ steps.get-version.outputs.version }}.zip
          tag: ${{ steps.get-version.outputs.version }}
          commit: ${{ github.sha }}
          replacesArtifacts: true
          allowUpdates: true
          draft: true
          makeLatest: true